"""user table

Revision ID: e6b006fa4a07
Revises: 4e4c227bb3e3
Create Date: 2025-12-06 16:44:05.751445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b006fa4a07'
down_revision: Union[str, None] = '4e4c227bb3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_drivers_login', table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('login', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password_sha256', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('employment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='drivers_pkey'),
    sa.UniqueConstraint('login', name='drivers_login_key')
    )
    op.create_index('ux_drivers_login', 'drivers', ['login'], unique=True)
    # ### end Alembic commands ###
